server:
  # 端口配置
  port: 8000
spring:
  # 发布profile
  profiles: "publish"
  # 数据库连接配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://120.79.153.123:3306/demo"
    username: "root"
    password: "retroLiA1."
  data:
    # MongoDB配置
    mongodb:
      database: "project"
      host: "172.27.0.5"
      port: 27017
  # rabbitMQ配置
  rabbitmq:
    host: "172.27.0.5"
    port: 5672
    username: "blogmanager"
    password: "123456"
  # Redis配置
  redis:
    host: 106.15.72.196
    port: 26379
    timeout: 50
    password: blogbadass
    jedis:
      pool:
        max-idle: 10
        max-wait: -1
        max-active: 10
  # Zipkin配置
  zipkin:
    base-url: http://localhost:9411/
  # sleuth配置
  sleuth:
    sampler:
      # 采样比例为100%，默认为10%
      probability: 1.0
# 配置hystrix防护机制
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
eureka:
  instance:
    prefer-ip-address: true
    hostname: 148.70.10.229
    instance-id: ${spring.application.name}:${server.port}
    # 设置IP地址
    ip-address: 148.70.10.229
  client:
    service-url:
      defaultZone: http://blogmanager:123456@47.101.201.93:10237/eureka/