server:
  # 端口配置
  port: 8000
spring:
  # 开发profile
  profiles: "dev"
  # 数据库连接配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://106.15.72.196:3306/demo"
    username: "root"
    password: "retroLiA1."
  data:
    # MongoDB配置
    mongodb:
      database: "blog"
      host: "106.15.72.196"
      port: 27017
      authentication-database: "blog"
      username: "blogmanager"
      password: "123456"
  # rabbitMQ配置
  rabbitmq:
    host: "106.15.72.196"
    port: 5672
    username: "blogmanager"
    password: "123456"
  # Redis配置
  redis:
    timeout: 50
    password: blogbadass
    jedis:
      pool:
        max-idle: 10
        max-wait: -1
        max-active: 10
    sentinel:
      master: blogmaster
      nodes: 106.15.72.196:26379

# 配置hystrix防护机制
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://blogmanager:123456@master:10237/eureka/