server:
  # 端口配置
  port: 8000
spring:
  # 发布profile
  profiles: "publish"
  # 数据库连接配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://120.79.153.123:3306/demo"
    username: "root"
    password: "retroLiA1."
  data:
    # MongoDB配置
    mongodb:
      database: "project"
      host: "172.27.0.5"
      port: 27017
  # rabbitMQ配置
  rabbitmq:
    host: "172.27.0.5"
    port: 5672
    username: "blogmanager"
    password: "123456"

# 配置hystrix防护机制
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 3000

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://blogmanager:123456@meloli.net:10237/eureka/